# Generated by Django 2.1.2 on 2019-10-03 03:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edge_History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=50)),
                ('updated_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('uuid', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Edge_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('build_status', models.IntegerField(default=2)),
                ('resource_type', models.CharField(default='vod', max_length=50)),
                ('status', models.IntegerField(default=1)),
                ('created_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Miss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_cdn', models.TextField(max_length=50)),
                ('miss_file', models.TextField(max_length=50)),
                ('time_updated', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('url_file', models.TextField(default='/usr/local/nginx-1.10.1/conf/sites-enabled/', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='edge_history',
            name='edge_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Edge_Histories', to='api.Edge_Info'),
        ),
    ]
