# Generated by Django 2.1.2 on 2019-10-03 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edge_history',
            name='uuid',
            field=models.TextField(max_length=50),
        ),
    ]
